### ISSUE TITLE
Variables to change the perlin noise?

### ISSUE THREAD

**Issue by Camden-Tech** [krubbles/Icaria-Noise#1]
Where is the scale, octave, lacunlarity, and persistence variables the method for the 2D perlin noise? Am I misunderstanding what this is intended for?

**Comment by Camden-Tech** [comment]
I see the octaves in the consts, but what about the other variables?

**Comment by krubbles** [comment]
Scale, octave, lacunarity, and persistence aren't parameters of Perlin noise, they are parameters of fractal noise which is made with Perlin noise. You can do it fairly easily like this: 

```
float total = 0, totalWeight = 0, weight = 1;
for (int i = 0; i < octaves; i++)
{
  total += weight * PerlinNoise(frequency);
  totalWeight += weight;
  weight *= persistence;
  frequency *= lacunarity;
}
return total * scale / totalWeight;
```

**Comment by Camden-Tech** [comment]
> Scale, octave, lacunarity, and persistence aren't parameters of Perlin noise, they are parameters of fractal noise which is made with Perlin noise. You can do it fairly easily like this:
> 
> ```
> float total = 0, totalWeight = 0, weight = 1;
> for (int i = 0; i < octaves; i++)
> {
>   total += weight * PerlinNoise(frequency);
>   totalWeight += weight;
>   weight *= persistence;
>   frequency *= lacunarity;
> }
> return total * scale / totalWeight;
> ```

Aah so I was misunderstanding something. Thanks, sorry I guess I was too used to other libraries and didn't understand it like I thought I did lol
